apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
parameters:
  type: gp2
  zones: eu-west-1a, eu-west-1b, eu-west-1c
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
