---
apiVersion: v1
kind: Service
metadata:
  name: loghouse
  namespace: {{ .Values.namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.loghouse_host }}
spec:
  selector:
    component: loghouse
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: {{ .Values.loghouse.service }}
